#!/usr/bin/env python3
"""Generate thin Codex custom-agent adapters from canonical Claude agents."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
SOURCE_DIR = REPO_ROOT / ".claude" / "agents"
TARGET_DIR = REPO_ROOT / ".codex" / "agents"

READ_ONLY_AGENTS = {
    "agent-review-agent",
    "design-review-agent",
    "hazard-scan-agent",
    "hazard-synthesis-agent",
    "premortem-agent",
    "refactor-design-agent",
    "refactor-duplication-agent",
    "refactor-mechanics-agent",
    "test-review-assertions-agent",
    "test-review-placement-agent",
    "test-review-selenium-agent",
    "test-review-statements-agent",
}


def parse_frontmatter(path: Path) -> dict[str, str]:
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    if not lines or lines[0] != "---":
        raise ValueError(f"{path}: missing opening YAML front matter delimiter")

    metadata: dict[str, str] = {}
    for line in lines[1:]:
        if line == "---":
            break
        key, separator, value = line.partition(":")
        if separator:
            metadata[key.strip()] = value.strip()
    else:
        raise ValueError(f"{path}: missing closing YAML front matter delimiter")

    for required in ("name", "description"):
        if not metadata.get(required):
            raise ValueError(f"{path}: missing required {required!r} field")
    return metadata


def toml_string(value: str) -> str:
    # JSON quoted strings are valid TOML basic strings for this content.
    return json.dumps(value, ensure_ascii=False)


def render_adapter(source: Path, metadata: dict[str, str]) -> str:
    relative_source = source.relative_to(REPO_ROOT).as_posix()
    name = metadata["name"]
    instructions = (
        f"Resolve the repository root, then read `{relative_source}` completely. "
        "Ignore only its YAML front matter and follow the Markdown body as your "
        "developer instructions. Also read "
        "`.claude/guidelines/platform-capabilities.md` completely and map every "
        "named capability to the equivalent Codex tool. Preserve workflow semantics "
        "when the canonical file mentions a Claude-specific tool name. If your "
        "sandbox is read-only and the canonical workflow requires appending "
        "`infrastructure/agent-progress.log`, send each milestone to the parent "
        "immediately as `AGENT_MILESTONE: <exact log line>`; the parent will append "
        "it on your behalf. Do not edit the canonical agent file unless the parent "
        "explicitly asks you to update the framework."
    )
    lines = [
        "# Generated by .codex/scripts/sync_claude_agents.py; do not edit.",
        f"name = {toml_string(name)}",
        f"description = {toml_string(metadata['description'])}",
        f"developer_instructions = {toml_string(instructions)}",
    ]
    if name in READ_ONLY_AGENTS:
        lines.append('sandbox_mode = "read-only"')
    return "\n".join(lines) + "\n"


def expected_adapters() -> dict[Path, str]:
    adapters: dict[Path, str] = {}
    for source in sorted(SOURCE_DIR.glob("*.md")):
        metadata = parse_frontmatter(source)
        target = TARGET_DIR / f"{metadata['name']}.toml"
        if target in adapters:
            raise ValueError(f"duplicate agent name: {metadata['name']}")
        adapters[target] = render_adapter(source, metadata)
    return adapters


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify generated adapters without changing files",
    )
    args = parser.parse_args()

    expected = expected_adapters()
    stale = sorted(TARGET_DIR.glob("*.toml")) if TARGET_DIR.exists() else []
    stale = [path for path in stale if path not in expected]
    mismatched = [
        path
        for path, content in expected.items()
        if not path.exists() or path.read_text(encoding="utf-8") != content
    ]

    if args.check:
        for path in mismatched:
            print(f"OUTDATED {path.relative_to(REPO_ROOT)}")
        for path in stale:
            print(f"STALE {path.relative_to(REPO_ROOT)}")
        return 1 if mismatched or stale else 0

    TARGET_DIR.mkdir(parents=True, exist_ok=True)
    for path, content in expected.items():
        path.write_text(content, encoding="utf-8")
        print(f"WROTE {path.relative_to(REPO_ROOT)}")
    for path in stale:
        path.unlink()
        print(f"REMOVED {path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
