#!/usr/bin/env bash
# Generates infrastructure/.env with ports isolated per repo instance.
# REPO_INDEX comes from the trailing digits of the repository directory name
# (uwords -> 0, uwords2 -> 2), or from REPO_INDEX in the environment.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INFRA_DIR="$(dirname "$SCRIPT_DIR")"
REPO_DIR="$(dirname "$INFRA_DIR")"
ENV_FILE="$INFRA_DIR/.env"

if [[ -f "$ENV_FILE" && "${FORCE:-0}" != "1" ]]; then
  echo "infrastructure/.env already exists — re-run with FORCE=1 to regenerate."
  exit 0
fi

repo_name="$(basename "$REPO_DIR")"
suffix="${repo_name##*[!0-9]}"
index="${REPO_INDEX:-${suffix:-0}}"

# Signing secret for access tokens; regenerated per repo instance.
jwt_secret="$(openssl rand -hex 32)"

cat > "$ENV_FILE" <<EOF
# Generated by infrastructure/scripts/setup-ports.sh for '$repo_name'.
REPO_INDEX=$index
COMPOSE_PROJECT_NAME=uwords-$index

BACKEND_HOST=0.0.0.0
BACKEND_PORT=$((8000 + index))
BACKEND_EXTERNAL_HOST=localhost

DB_HOST=localhost
DB_PORT=$((5432 + index))
DB_NAME=uwords
DB_USER=uwords
DB_PASSWORD=uwords

REDIS_HOST=localhost
REDIS_PORT=$((6379 + index))
REDIS_PASSWORD=uwords

MAIL_HOST=localhost
MAIL_PORT=$((1025 + index))
MAIL_SENDER=no-reply@uwords.local
MAIL_TIMEOUT_MILLIS=60000
MAILHOG_HTTP_PORT=$((8025 + index))

# Browser origins allowed on /api/**; the local frontend dev server lives on 5173 + index.
CORS_ALLOWED_ORIGINS=http://localhost:$((5173 + index))

AUTH_CHALLENGE_TTL_SECONDS=300
AUTH_CHALLENGE_MAX_ATTEMPTS=5
AUTH_CHALLENGE_REPLAY_WINDOW_SECONDS=60
# Local development only: every issued e-mail code is this value. Never set in prod-copy or production.
AUTH_CHALLENGE_FIXED_CODE=111111
ACCESS_TOKEN_TTL_SECONDS=1800
REFRESH_TOKEN_TTL_SECONDS=31536000
JWT_SECRET=$jwt_secret
EOF

echo "Wrote $ENV_FILE (REPO_INDEX=$index, BACKEND_PORT=$((8000 + index)), DB_PORT=$((5432 + index)))"
