#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INFRA_DIR="$(dirname "$SCRIPT_DIR")"
BOT_DIR="$(dirname "$INFRA_DIR")"
REPO_DIR="$(dirname "$BOT_DIR")"
ENV_FILE="$INFRA_DIR/.env"
API_ENV="$REPO_DIR/infrastructure/.env"

if [[ -f "$ENV_FILE" && "${FORCE:-0}" != "1" ]]; then
  echo "$ENV_FILE already exists — re-run with FORCE=1 to regenerate."
  exit 0
fi

repo_name="$(basename "$REPO_DIR")"
suffix="${repo_name##*[!0-9]}"
index="${REPO_INDEX:-${suffix:-0}}"

if [[ -f "$API_ENV" ]]; then
  api_index="$(sed -n 's/^REPO_INDEX=//p' "$API_ENV")"
  if [[ -n "$api_index" ]]; then
    index="$api_index"
  fi
fi

cat > "$ENV_FILE" <<EOF
# Generated by bot/infrastructure/scripts/setup-ports.sh for '$repo_name'.
REPO_INDEX=$index
COMPOSE_PROJECT_NAME=uwords-bot-$index

BOT_HOST=0.0.0.0
BOT_PORT=$((18000 + index))
BOT_EXTERNAL_HOST=localhost

BOT_DB_PORT=$((16432 + index))
BOT_REDIS_PORT=$((17379 + index))
BOT_ADMINER_PORT=$((19080 + index))

DB_HOST=db
DB_PORT=5432
DB_NAME=uwords
DB_USER=postgres
DB_PASSWORD=postgres

REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=uwords
REDIS_DB=0
EOF

echo "Wrote $ENV_FILE (REPO_INDEX=$index, BOT_PORT=$((18000 + index)), BOT_DB_PORT=$((16432 + index)), BOT_REDIS_PORT=$((17379 + index)))"
