#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INFRA_DIR="$(dirname "$SCRIPT_DIR")"
FRONTEND_DIR="$(dirname "$INFRA_DIR")"
REPO_DIR="$(dirname "$FRONTEND_DIR")"
ENV_FILE="$INFRA_DIR/.env"
API_ENV="$REPO_DIR/infrastructure/.env"

if [[ -f "$ENV_FILE" && "${FORCE:-0}" != "1" ]]; then
  echo "$ENV_FILE already exists — re-run with FORCE=1 to regenerate."
  exit 0
fi

repo_name="$(basename "$REPO_DIR")"
suffix="${repo_name##*[!0-9]}"
index="${REPO_INDEX:-${suffix:-0}}"

if [[ -f "$API_ENV" ]]; then
  api_index="$(sed -n 's/^REPO_INDEX=//p' "$API_ENV")"
  if [[ -n "$api_index" ]]; then
    index="$api_index"
  fi
fi

cat > "$ENV_FILE" <<ENV
# Generated by frontend/infrastructure/scripts/setup-ports.sh for '$repo_name'.
REPO_INDEX=$index

FRONTEND_HOST=127.0.0.1
FRONTEND_PORT=$((5173 + index))
FRONTEND_EXTERNAL_HOST=localhost

E2E_HEADLESS=true
E2E_API_STUB_PORT=$((8173 + index))
ENV

echo "Wrote $ENV_FILE (REPO_INDEX=$index, FRONTEND_PORT=$((5173 + index)))"
